spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test?autoReconnect=true
    username: sa
    password:
  jpa:
    database: mysql
    hibernate:
        ddl-auto: none
        naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jackson:
    serialization:
      indent_output: true
server:
  servlet:
    contextPath: /v1